kind: Service
apiVersion: v1
metadata:
  name: "flaskapp1"
  namespace: web
spec:
  selector:
    app: "flaskapp1"
  ports:
    - protocol: "TCP"
      port: 5001
      targetPort: 5001
  type: NodePort
